name: CI

on: [push]

jobs:
  Macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install packages
        run: brew install gcovr ninja libmagic
      - name: Install python modules
        run: pip3 install meson==0.49.2 pytest
      - name: Install deps
        shell: bash
        run: |
          ARCHIVE_NAME=deps2_osx_native_dyn_zim-tools.tar.xz
          wget -O- http://tmp.kiwix.org/ci/${ARCHIVE_NAME} | tar -xJ -C $HOME
      - name: Compile
        shell: bash
        run: |
          export PKG_CONFIG_PATH=$HOME/BUILD_native_dyn/INSTALL/lib/pkgconfig
          meson . build
          cd build
          ninja


  Linux:
    strategy:
      fail-fast: false
      matrix:
        target:
          - native_static
          - native_dyn
          - win32_static
          - win32_dyn
        include:
          - target: native_static
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: native_dyn
            image_variant: xenial
            lib_postfix: '/x86_64-linux-gnu'
          - target: win32_static
            image_variant: f31
            lib_postfix: '64'
          - target: win32_dyn
            image_variant: f31
            lib_postfix: '64'

    env:
      HOME: /home/runner
    runs-on: ubuntu-latest
    container:
      image: "kiwix/kiwix-build_ci:${{matrix.image_variant}}-26"
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Checkout code
      shell: python
      run: |
        from subprocess import check_call
        from os import environ
        config_command = [
          'git', 'config', '--global',
          'http.postBuffer', '1048576000'
        ]
        check_call(config_command, cwd=environ['HOME'])
        clone_command = [
          'git', 'clone',
          'https://github.com/${{github.repository}}',
          '--depth=1',
          '--branch', '${{steps.extract_branch.outputs.branch}}'
        ]
        check_call(clone_command, cwd=environ['HOME'])
    - name: Install deps
      shell: bash
      run: |
        ARCHIVE_NAME=deps2_${OS_NAME}_${{matrix.target}}_zim-tools.tar.xz
        wget -O- http://tmp.kiwix.org/ci/${ARCHIVE_NAME} | tar -xJ -C /home/runner
    - name: Compile
      shell: bash
      run: |
        if [[ "${{matrix.target}}" =~ .*_static ]]; then
          MESON_OPTION="-Dstatic-linkage=true"
        fi
        if [[ ! "${{matrix.target}}" =~ native_.* ]]; then
          MESON_OPTION="$MESON_OPTION --cross-file $HOME/BUILD_${{matrix.target}}/meson_cross_file.txt"
        fi
        cd $HOME/zim-tools
        meson . build ${MESON_OPTION} -Db_coverage=true
        cd build
        ninja
      env:
        PKG_CONFIG_PATH: "/home/runner/BUILD_${{matrix.target}}/INSTALL/lib/pkgconfig:/home/runner/BUILD_${{matrix.target}}/INSTALL/lib${{matrix.lib_postfix}}/pkgconfig"
    - name: Test
      shell: bash
      run: |
       cd $HOME/zim-tools/build
       meson test --verbose
       ninja coverage
    - name: Publish coverage
      shell: bash
      run: |
        cd $HOME/zim-tools
        curl https://codecov.io/bash -o codecov.sh
        bash codecov.sh -n "${OS_NAME}_${{matrix.target}}" -Z
        rm codecov.sh
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
