name: Docker

on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@v3
        with:
          image-path: openzim/zim-tools
          tag-pattern: /^([0-9.]+)$/
          latest-on-tag: true
          restrict-to: openzim/zim-tools
          dockerfile: docker/Dockerfile
          build-args:
            VERSION: {version}
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
